### ISSUE TITLE
ProtooClient.Peer.on('notification', listener) is missing from documentation

### ISSUE THREAD

**Issue by antoniom** [ibc/protoojs.org#1]
Since `room.spread()` sends a notification rather than a request from v3 I was unable to find how to handle the notifications from the client side.
After some research I have noticed that `ProtooClient.Peer.on('notification', listener)` is available but not documented on the website.
Can you add it please?

**Comment by ibc** [comment]
Yes, I'll update the doc in the web in the next days.
Thanks.

**Comment by ibc** [comment]
Done. Thanks.
